#!/bin/bash

busybox httpd -p 127.0.0.1:8080 -h /app/webroot

while true; do
    xinit ./ENTRYX -- -retro -dpms
    echo "Terminated exit code $?"
    echo "10 seconds to restart..."
    sleep 10
done
